# Generated by Django 5.1.4 on 2024-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_price_calculations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='medicaments',
        ),
        migrations.AddField(
            model_name='commande',
            name='medicaments',
            field=models.ManyToManyField(through='gestion.LigneCommande', to='gestion.medicament'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Expédiée', 'Expédiée'), ('Annulée', 'Annulée')], default='En attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='LigneFacture',
        ),
    ]
