# Generated by Django 5.1.4 on 2024-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_facture_medicaments_commande_medicaments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remise en pourcentage (ex: 10 pour 10%)', max_digits=5),
        ),
    ]
