# Generated by Django 5.1.4 on 2024-12-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_facture_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='plafond_credit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='est_payee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('ESP', 'Espèces'), ('CB', 'Carte Bancaire'), ('CHQ', 'Chèque'), ('CRD', 'Crédit')], max_length=3)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.facture')),
            ],
        ),
    ]
