# Generated by Django 5.1.4 on 2024-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_client_credit_client_plafond_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='methode_paiement',
            field=models.CharField(choices=[('ESP', 'Espèces'), ('CB', 'Carte Bancaire'), ('CHQ', 'Chèque'), ('CRD', 'Crédit')], default='ESP', max_length=3),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
